### ISSUE TITLE
您好，可以有时间适配一下刚出的yi-chat模型吗？谢谢！

### ISSUE THREAD

**Issue by Hapluckyy** [ssbuild/aigc_serving#141]
参考链接：https://huggingface.co/01-ai/Yi-34B-Chat-4bits

十分感谢

**Comment by ssbuild** [comment]
pip install transformers>=4.35.*   , 应该可以直接跑

**Comment by Hapluckyy** [comment]
好像不行，请问模型名称应该写什么呢？
我尝试直接使用了yi作为模型名称，提示我需要安装 autoawq这个python package，安装之后也还是会报错

**Comment by Hapluckyy** [comment]
我的config.yaml是这么写的：
```
serve_args:
  host: 0.0.0.0
  port: 8081
  # http 工作进程
  workers: 1

    #  api_keys: []
  api_keys:
    - edge123456



yi:
  alias: null
  # 当仅有一个lora, 是否自动合并成一个模型，此方法将无法调用基础模型，只能使用合并后的权重
  auto_merge_lora_single: true
  # 是否自动量化模型
  auto_quantize: true
  # 是否启用
  enable: true
  # embdding max batch size
  max_batch_size: 1
  model_config:
    do_lower_case: null
    # 是否启用lora , 多个 lora , adapter_name: lora weight dir
    # "default": "/data/nlp/pre_models/torch/lora_path_dir"
    # "your_adapter_name": "/data/nlp/pre_models/torch/your_adapter_dir"
    lora: {}
    model_name_or_path: /aigc_serving/yi
    model_type: yi
    use_fast_tokenizer: false
  # 扩展位置长度 1 即为 1 * 2048 不扩充 , 2 即为 2 * 2 * 2048 以此类推
  ntk_scale: 1

  # one of deepspeed,accelerate,hf    单卡建议使用 hf
  work_mode: hf
```

报错为：
```
None
ModelArguments(model_name_or_path='/aigc_serving/yi', model_type='yi', config_overrides=None, config_name=None, tokenizer_name=None, processer_name=None, imageprocesser_name=None, feature_extractor_name=None, cache_dir=None, do_lower_case=None, use_fast_tokenizer=False, model_revision='main', use_auth_token=False, gradient_checkpointing=False, gradient_checkpointing_kwargs=None, model_custom={})
Traceback (most recent call last):
  File "/aigc_serving/serving/workers/llm_worker.py", line 109, in run_begin
    self.api_client.init()
  File "/aigc_serving/serving/model_handler/base/infer.py", line 101, in init
    self.init_model()
  File "/aigc_serving/serving/model_handler/base/infer.py", line 113, in init_model
    self.model, self.config, self.tokenizer = call_method(device_id)
  File "/aigc_serving/serving/model_handler/yi/infer.py", line 45, in _load_model
    pl_model = MyTransformer(config=config, model_args=model_args, torch_dtype=config.torch_dtype, rope_args=rope_args)
  File "/usr/local/lib/python3.10/dist-packages/aigc_zoo/utils/transformer_utils.py", line 8, in hf_fn
    fn(self,*args,**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aigc_zoo/model_zoo/llm/llm_model.py", line 44, in __init__
    super(MyTransformer, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/models/transformer_base.py", line 273, in __init__
    self.set_model(self.__BACKBONE_CLASS__[0](*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/aigc_zoo/model_zoo/llm/llm_model.py", line 15, in __init__
    super(TransformerForLM, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/models/transformer.py", line 79, in __init__
    self.set_model(self.from_pretrained(model_class or AutoModelForCausalLM, *args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/models/transformer_base.py", line 182, in from_pretrained
    cls_ = CLS.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2826, in from_pretrained
    raise ImportError("Loading an AWQ quantized model requires auto-awq library (`pip install autoawq`)")
ImportError: Loading an AWQ quantized model requires auto-awq library (`pip install autoawq`)
ERROR:root:Loading an AWQ quantized model requires auto-awq library (`pip install autoawq`)
```

安装autoawq之后的报错为：
```
INFO:numexpr.utils:Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/aigc_serving/serving/workers/llm_worker.py", line 109, in run_begin
    self.api_client.init()
  File "/aigc_serving/serving/model_handler/base/infer.py", line 101, in init
    self.init_model()
  File "/aigc_serving/serving/model_handler/base/infer.py", line 113, in init_model
    self.model, self.config, self.tokenizer = call_method(device_id)
  File "/aigc_serving/serving/model_handler/yi/infer.py", line 45, in _load_model
    pl_model = MyTransformer(config=config, model_args=model_args, torch_dtype=config.torch_dtype, rope_args=rope_args)
  File "/usr/local/lib/python3.10/dist-packages/aigc_zoo/utils/transformer_utils.py", line 8, in hf_fn
    fn(self,*args,**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/aigc_zoo/model_zoo/llm/llm_model.py", line 44, in __init__
    super(MyTransformer, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/models/transformer_base.py", line 273, in __init__
    self.set_model(self.__BACKBONE_CLASS__[0](*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/aigc_zoo/model_zoo/llm/llm_model.py", line 15, in __init__
    super(TransformerForLM, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/models/transformer.py", line 79, in __init__
    self.set_model(self.from_pretrained(model_class or AutoModelForCausalLM, *args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/deep_training/nlp/models/transformer_base.py", line 182, in from_pretrained
    cls_ = CLS.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3319, in from_pretrained
    model, has_been_replaced = replace_with_awq_linear(
  File "/usr/local/lib/python3.10/dist-packages/transformers/integrations/awq.py", line 62, in replace_with_awq_linear
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "/usr/local/lib/python3.10/dist-packages/awq/__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "/usr/local/lib/python3.10/dist-packages/awq/models/__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "/usr/local/lib/python3.10/dist-packages/awq/models/mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "/usr/local/lib/python3.10/dist-packages/awq/models/base.py", line 12, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "/usr/local/lib/python3.10/dist-packages/awq/quantize/quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "/usr/local/lib/python3.10/dist-packages/awq/modules/linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
ERROR:root:libcudart.so.12: cannot open shared object file: No such file or directory
```

**Comment by ssbuild** [comment]
1. auto_quantize: true 改为false ,  两种量化方法不一样。
2. 安装cuda 12.1 , torch 2.1.0，  重新建立环境，安装requirement依赖。

**Comment by Hapluckyy** [comment]
谢谢，问题解决啦！

**Comment by Hapluckyy** [comment]
您好，我在克隆新的代码之后，部署yi 34b 4bit chat遇到了问题：

按照您给出的template，我把config.yaml 修改为了以下内容：
```
Yi-34B-Chat:
  alias: null
  # 当仅有一个lora, 是否自动合并成一个模型，此方法将无法调用基础模型，只能使用合并后的权重
  auto_merge_lora_single: false
  # 是否自动量化模型
  auto_quantize: false
  # 是否启用
  enable: true
  # embdding max batch size
  max_batch_size: 1
  model_config:
    do_lower_case: null
    # 是否启用lora , 多个 lora , adapter_name: lora weight dir
    # "default": "/data/nlp/pre_models/torch/lora_path_dir"
    # "your_adapter_name": "/data/nlp/pre_models/torch/your_adapter_dir"
    lora: {}
    model_name_or_path: /aigc_serving/yi
    model_type: llama
    use_fast_tokenizer: false
  # 扩展位置长度 1 即为 1 * 2048 不扩充 , 2 即为 2 * 2 * 2048 以此类推
  ntk_scale: 1

  # one of deepspeed,accelerate,hf    单卡建议使用 hf
  work_mode: deepspeed


  workers:
  # 第一个worker
  - device_id:
    # 使用第一块和第二块显卡
    - 0
```

现在的报错是：
```

None
ModelArguments(model_name_or_path='/aigc_serving/yi', model_type='llama', config_overrides=None, config_name=None, tokenizer_name=None, processer_name=None, imageprocesser_name=None, feature_extractor_name=None, cache_dir=None, do_lower_case=None, use_fast_tokenizer=False, model_revision='main', use_auth_token=False, gradient_checkpointing=False, gradient_checkpointing_kwargs=None, model_custom={})
You have loaded an AWQ model on CPU and have a CUDA device available, make sure to set your model on a GPU device in order to run your model.

```
似乎无法加载模型到显卡，请问应该怎么解决呢

**Comment by Hapluckyy** [comment]
完整报错：
```
bash start.sh 
INFO:root:WokerLoader create...
INFO:root:group name ai_group_Yi-34B-Chat ,worker id 0
INFO:root:Yi-34B-Chat worker pid 440...
INFO:     Started server process [383]
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
[I debug.cpp:49] [c10d] The debug level is set to INFO.
[2023-11-28 09:54:43,188] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[I socket.cpp:452] [c10d - debug] The server socket will attempt to listen on an IPv6 address.
[I socket.cpp:502] [c10d - debug] The server socket is attempting to listen on [::]:33079.
[I socket.cpp:576] [c10d] The server socket has started to listen on [::]:33079.
[I TCPStore.cpp:252] [c10d - debug] The server has started on port = 33079.
[I socket.cpp:686] [c10d - debug] The client socket will attempt to connect to an IPv6 address of (127.0.0.1, 33079).
[I socket.cpp:297] [c10d - debug] The server socket on [::]:33079 has accepted a connection from [localhost.lan]:41822.
[I socket.cpp:849] [c10d] The client socket has connected to [localhost.lan]:33079 on [localhost.lan]:41822.
[I TCPStore.cpp:261] [c10d - debug] TCP client connected to host 127.0.0.1:33079
[I ProcessGroupNCCL.cpp:687] [Rank 0] ProcessGroupNCCL initialization options:NCCL_ASYNC_ERROR_HANDLING: 1, NCCL_DESYNC_DEBUG: 0, NCCL_ENABLE_TIMING: 0, NCCL_BLOCKING_WAIT: 0, TIMEOUT(ms): 1800000, USE_HIGH_PRIORITY_STREAM: 0, TORCH_DISTRIBUTED_DEBUG: INFO, NCCL_DEBUG: OFF, ID=94261262183728
LlamaConfig {
  "_name_or_path": "/aigc_serving/yi",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "bos_token_id": 6,
  "do_sample": true,
  "eos_token_id": 7,
  "hidden_act": "silu",
  "hidden_size": 7168,
  "initializer_range": 0.02,
  "intermediate_size": 20480,
  "max_length": 4096,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 56,
  "num_hidden_layers": 60,
  "num_key_value_heads": 8,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "quantization_config": {
    "bits": 4,
    "group_size": 128,
    "quant_method": "awq",
    "version": "gemm",
    "zero_point": true
  },
  "return_dict": false,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 5000000.0,
  "task_specific_params": {},
  "temperature": 0.6,
  "tie_word_embeddings": false,
  "top_p": 0.8,
  "torch_dtype": "float16",
  "transformers_version": "4.35.2",
  "use_cache": true,
  "vocab_size": 64000
}

None
ModelArguments(model_name_or_path='/aigc_serving/yi', model_type='llama', config_overrides=None, config_name=None, tokenizer_name=None, processer_name=None, imageprocesser_name=None, feature_extractor_name=None, cache_dir=None, do_lower_case=None, use_fast_tokenizer=False, model_revision='main', use_auth_token=False, gradient_checkpointing=False, gradient_checkpointing_kwargs=None, model_custom={})
You have loaded an AWQ model on CPU and have a CUDA device available, make sure to set your model on a GPU device in order to run your model.
```

**Comment by ssbuild** [comment]
看了下，应该只是个警告，应该不影响，测测是否正常

**Comment by ssbuild** [comment]
1. 已支持autoawq ， 更新程序， 再试试。
2.  如果提示下面的信息，忽略即可。只是无用警告。
You have loaded an AWQ model on CPU and have a CUDA device available, make sure to set your model on a GPU device in order to run your model.
