### ISSUE TITLE
在windows环境下运行aigc_serving-main\serving\main.py文件报创建新进程的错误。

### ISSUE THREAD

**Issue by xiaochaich** [ssbuild/aigc_serving#22]
具体报错信息如下：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\duoduo\aigc_serving-main\serving\main.py", line 12, in <module>
    from serving.serve.backend import WokerLoader
  File "H:\duoduo\aigc_serving-main\serving\serve\backend.py", line 7, in <module>
    from serving.workers import llm_worker
  File "H:\duoduo\aigc_serving-main\serving\workers\llm_worker.py", line 10, in <module>
    from ipc_worker.ipc_zmq_loader import IPC_zmq,ZMQ_process_worker  # noqa
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\site-packages\ipc_worker\ipc_zmq_loader.py", line 6, in <module>
    from .zmq_module import IPC_zmq,ZMQ_process_worker
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\site-packages\ipc_worker\zmq_module\__init__.py", line 5, in <module>
    from .ipc_zmq import IPC_zmq,ZMQ_process_worker
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\site-packages\ipc_worker\zmq_module\ipc_zmq.py", line 34, in <module>
    class IPC_zmq:
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\site-packages\ipc_worker\zmq_module\ipc_zmq.py", line 40, in IPC_zmq
    evt_quit=multiprocessing.Manager().Event(),
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\managers.py", line 562, in start
    self._process.start()
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\ProgramData\Anaconda3\envs\aigc_serving\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

请问大佬，这个应该怎么解决？

**Comment by ssbuild** [comment]
建议使用windows 子系统 ubuntu, 或者Linux
