### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by shell-nlp** [ssbuild/aigc_serving#29]
AttributeError: 'LoraModule' object has no attribute 'add_adapter'
AttributeError: 'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'

定位：
https://github.com/ssbuild/deep_training/blob/b350ea5f2e3c9866fac922fc61c368e49e0a9f69/src/deep_training/nlp/models/petl/lora/petl_model.py#L286C29-L286C29

确实不存在 add_adapter

**Comment by ssbuild** [comment]
是peft 的权重吧？

**Comment by shell-nlp** [comment]
我使用 chatglm2_finetuning 训练出来的权重， 不过chatglm2_finetuning 项目很久没更新

` "chatglm2-6b": {
        "enable": True,
        "work_mode": "deepspeed",  # one of deepspeed,accelerate,hf
        "workers": [
            {
                "device_id": [0,1,2,3]  # 默认启动一个worker , 使用第一块显卡
            }
        ],
        
        "auto_quantize": False, # 是否自动量化模型
        "auto_merge_lora_single": False, # 当仅有一个lora, 是否自动合并成一个模型，此方法将无法调用基础模型，只能使用合并后的权重
        "ntk_scale": 1, #  扩展位置长度 1 即为 1 * 2048 不扩充 , 4 即为 4 * 2048 以此类推
        "max_batch_size": 1, # embdding max batch size
        "model_config": {
            "model_type": "chatglm2",
            "model_name_or_path": "/home/dev/model/chatglm2-6B",
            "use_fast_tokenizer": False,
            "do_lower_case": None,
            "lora": {
                "e4": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=4-step=235",
                "e5": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=5-step=282",
                "e7": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=7-step=376",
                "e8": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=8-step=423",
            }
        }

    },`
希望加一下你的微信， 方便交流    我们主要使用你的框架 进行 实验

**Comment by shell-nlp** [comment]
这 aofc_serving 对应的报错位置 
aigc_serving/serving/model_handler/chatglm2/infer.py", line 117, in _load_lora_model
    pl_model.load_sft_weight(ckpt_dir, adapter_name=adapter_name, lora_config=config,map_preprocess=default_peft_weight_preprocess)

**Comment by shell-nlp** [comment]
> 是peft 的权重吧？

是你项目的 lora 权重， 不是 peft格式的权重，  只要开启 配置 文件中的  “lora"  key 就报错

**Comment by ssbuild** [comment]
更新了，试一下 ，如果不行的话， 随便上传一个lora 的配置文件 ， 应该是lora 配置不太对， 没挂上lora_model ，

**Comment by ssbuild** [comment]
更新了，试一下，如果报错，随便上传一个lora 的配置文件看看。

**Comment by ssbuild** [comment]
> 我使用 chatglm2_finetuning 训练出来的权重， 不过chatglm2_finetuning 项目很久没更新
> 
> ` "chatglm2-6b": { "enable": True, "work_mode": "deepspeed", # one of deepspeed,accelerate,hf "workers": [ { "device_id": [0,1,2,3] # 默认启动一个worker , 使用第一块显卡 } ],
> 
> ```
>     "auto_quantize": False, # 是否自动量化模型
>     "auto_merge_lora_single": False, # 当仅有一个lora, 是否自动合并成一个模型，此方法将无法调用基础模型，只能使用合并后的权重
>     "ntk_scale": 1, #  扩展位置长度 1 即为 1 * 2048 不扩充 , 4 即为 4 * 2048 以此类推
>     "max_batch_size": 1, # embdding max batch size
>     "model_config": {
>         "model_type": "chatglm2",
>         "model_name_or_path": "/home/dev/model/chatglm2-6B",
>         "use_fast_tokenizer": False,
>         "do_lower_case": None,
>         "lora": {
>             "e4": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=4-step=235",
>             "e5": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=5-step=282",
>             "e7": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=7-step=376",
>             "e8": "/home/dev/project/chatglm2_finetuning/best_ckpt_react_data/epoch=8-step=423",
>         }
>     }
> 
> },`
> ```
> 
> 希望加一下你的微信， 方便交流 我们主要使用你的框架 进行 实验

微信号 IIIIxuexi

**Comment by shell-nlp** [comment]
adapter_congif.json :
```
{
  "base_model_name_or_path": null,
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "layers_pattern": null,
  "layers_to_transform": null,
  "lora_alpha": 128,
  "lora_dropout": 0.05,
  "lora_type": "lora",
  "modules_to_save": null,
  "r": 64,
  "target_dtype": null,
  "target_modules": [
    "query_key_value"
  ],
  "with_lora": true
}
```
仍然报错

**Comment by ssbuild** [comment]
错误的日志发一下吧

**Comment by shell-nlp** [comment]
```
INFO:aigc_zoo.model_zoo.chatglm2.llm_model:new_num_tokens:65024
============================================================ lora info
trainable params: 0 || all params: 6,259,181,568 || trainable%: 0.0
Traceback (most recent call last):
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 277, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModule' object has no attribute 'add_adapter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 132, in worker_ds
    self.init_model()
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 109, in init_model
    self.model, self.config, self.tokenizer = call_method(device_id)
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/chatglm2/infer.py", line 104, in _load_lora_model
    pl_model.load_sft_weight(ckpt_dir, adapter_name=adapter_name, lora_config=lora_args,map_preprocess=default_peft_weight_preprocess)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/trainer/pl/modelweighter.py", line 86, in load_sft_weight
    lora_model.load_adapter(sft_weight_path,
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 313, in load_adapter
    self.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 286, in add_adapter
    self.base_model.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 279, in __getattr__
    return getattr(self.model, name)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
INFO:root:'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
============================================================ lora info
trainable params: 0 || all params: 6,259,181,568 || trainable%: 0.0
Traceback (most recent call last):
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 277, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModule' object has no attribute 'add_adapter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 132, in worker_ds
    self.init_model()
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 109, in init_model
    self.model, self.config, self.tokenizer = call_method(device_id)
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/chatglm2/infer.py", line 104, in _load_lora_model
    pl_model.load_sft_weight(ckpt_dir, adapter_name=adapter_name, lora_config=lora_args,map_preprocess=default_peft_weight_preprocess)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/trainer/pl/modelweighter.py", line 86, in load_sft_weight
    lora_model.load_adapter(sft_weight_path,
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 313, in load_adapter
    self.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 286, in add_adapter
    self.base_model.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 279, in __getattr__
    return getattr(self.model, name)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
INFO:root:'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
============================================================ lora info
trainable params: 0 || all params: 6,259,181,568 || trainable%: 0.0
Traceback (most recent call last):
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 277, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModule' object has no attribute 'add_adapter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 132, in worker_ds
    self.init_model()
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 109, in init_model
    self.model, self.config, self.tokenizer = call_method(device_id)
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/chatglm2/infer.py", line 104, in _load_lora_model
    pl_model.load_sft_weight(ckpt_dir, adapter_name=adapter_name, lora_config=lora_args,map_preprocess=default_peft_weight_preprocess)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/trainer/pl/modelweighter.py", line 86, in load_sft_weight
    lora_model.load_adapter(sft_weight_path,
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 313, in load_adapter
    self.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 286, in add_adapter
    self.base_model.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 279, in __getattr__
    return getattr(self.model, name)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
INFO:root:'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
[I ProcessGroupNCCL.cpp:844] [Rank 1] NCCL watchdog thread terminated normally
============================================================ lora info
trainable params: 0 || all params: 6,259,181,568 || trainable%: 0.0
Traceback (most recent call last):
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 277, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LoraModule' object has no attribute 'add_adapter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 132, in worker_ds
    self.init_model()
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/base/infer.py", line 109, in init_model
    self.model, self.config, self.tokenizer = call_method(device_id)
  File "/home/dev/liuyu/git_dir/aigc_serving/serving/model_handler/chatglm2/infer.py", line 104, in _load_lora_model
    pl_model.load_sft_weight(ckpt_dir, adapter_name=adapter_name, lora_config=lora_args,map_preprocess=default_peft_weight_preprocess)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/trainer/pl/modelweighter.py", line 86, in load_sft_weight
    lora_model.load_adapter(sft_weight_path,
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 313, in load_adapter
    self.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/petl_model.py", line 286, in add_adapter
    self.base_model.add_adapter(adapter_name, lora_config)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/deep_training/nlp/models/petl/lora/lora_model.py", line 279, in __getattr__
    return getattr(self.model, name)
  File "/home/dev/anaconda3/envs/aigc_dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
INFO:root:'MyTransformerChatGlmLMHeadModel' object has no attribute 'add_adapter'
[I ProcessGroupNCCL.cpp:844] [Rank 2] NCCL watchdog thread terminated normally
[I ProcessGroupNCCL.cpp:844] [Rank 3] NCCL watchdog thread terminated normally
[I ProcessGroupNCCL.cpp:844] [Rank 0] NCCL watchdog thread terminated normally

```
