### ISSUE TITLE
NameError: name 'get_chat_default' is not defined

### ISSUE THREAD

**Issue by Qcosmo** [ssbuild/aigc_serving#93]
Traceback (most recent call last):
  File "/data/aigc_serving/serving/workers/llm_worker.py", line 132, in run_once
    node = self.api_client.trigger(r)
  File "/data/aigc_serving/serving/model_handler/base/infer.py", line 414, in trigger
    return self._do_work(r)
  File "/data/aigc_serving/serving/model_handler/base/infer.py", line 385, in _do_work
    node: CompletionResult = method_fn(query, history=history, **params)
  File "/data/aigc_serving/serving/model_handler/llama/infer.py", line 177, in chat
    prompt = get_chat_default(self.tokenizer, query, history)
NameError: name 'get_chat_default' is not defined

**Comment by ssbuild** [comment]
是不是没更新~

**Comment by Qcosmo** [comment]
是的，更新了之后好了。
